### ISSUE TITLE
seg fault when using stackusage

### ISSUE THREAD

**Issue by dpelle** [d99kris/stackusage#1]
I just discovered this tool which looks useful.
Unfortunately, it does not work for me on Ubuntu-16.04:

I built and installed as described in the doc:

```
$ git clone https://github.com/d99kris/stackusage && cd stackusage
$ mkdir -p build && cd build && cmake .. && make -s
sudo make install
```

This went fine. However, when trying to use it it crashes:

```
$ ./sutest01 
Starting thread size=16384 usage=0
Starting thread size=20480 usage=4096
Starting thread size=24576 usage=8192
Starting thread size=32768 usage=16384
Starting thread size=49152 usage=32768

$ stackusage ./sutest01 
/usr/local/bin/stackusage: line 153: 22008 Segmentation fault      (core dumped) SU_FILE="${TMPLOG}" LD_PRELOAD="${LIBPATH}" "${@:1}"
error: unable to preload libstackusage
```

Is there a know issue?

I also tried this:

```
$ LD_PRELOAD="/usr/local/lib/libstackusage.so" ./sutest01
Segmentation fault (core dumped)
```

Not sure how I can debug when using LD_PRELOAD=... to get
a stack trace for example.

**Comment by dpelle** [comment]
Just to add that I installed the stackusage tool on 2 hosts (both up-to-date x86_64 ubuntu-16.04 machines) and I get a similar segfault as described in previous comment on both machines when trying to run stackusage with the test program sutest01, or with any other program.

**Comment by d99kris** [comment]
Thanks for reporting the problem. Looks like Linux has changed how the process stack is being allocated. In older versions I've seen all memory up to the soft limit (for example 8MB) being pre-allocated, but I think in recent kernel versions it's allocated in 128KB pages. Possibly related to the "stack clash vulnerability" back in June. Anyway, I've patched stackusage (see the commit above) and based on my testing it should work fine in Ubuntu 16.04 LTS (and other systems with up-to-date kernels). Please let me know if you still see any problems, thanks!

**Comment by dpelle** [comment]
@d99kris wrote:

> Anyway, I've patched stackusage (see the commit above) and based
> on my testing it should work fine in Ubuntu 16.04 LTS (and other
> systems with up-to-date kernels).
> Please let me know if you still see any problems, thanks!

Excellent.  It works like a charm so far now.
Very useful tool with no noticeable overhead.
