### ISSUE TITLE
Support for -m32

### ISSUE THREAD

**Issue by stefanct** [d99kris/stackusage#8]
Since this tools is particularly useful for evaluating software destined for embedded systems while running it on desktops it would be great to support `-m32` (and `-mx32`) binaries because they make the numbers more precise for typical 32-bit embedded architectures.

If you try to run such a binary right now you would get:

    ERROR: ld.so: object '…/build/libstackusage.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

Interestingly, there does not seem to be a proper error handling that stops execution at that point but the binary gets executed just fine afterwards, trailed by a funny-looking error message:

    error: unable to preload libstackusage.so

To get it to work (but break ordinary binaries) one can simply append `-m32` to the `CMAKE_C_FLAGS` in `CMakeLists.txt`.

I have not looked at the code and don't have time to properly implement this (and I am fine with the mentioned workaround) but at least this limitation is documented now. Thank you - the tool is very useful!

**Comment by d99kris** [comment]
Hi @stefanct - thanks for reporting the issue, doing the troubleshooting and providing a workaround! 

I'll try take a look at this eventually, and see how I can make it more user-friendly. Possibly libstackusage.so could be built for both architectures, and then the appropriate so-file is selected automatically depending on executable type. Or at the very least a descriptive error message should be presented, with suggested workaround. I'll update here again once I find some time to work on this.

**Comment by d99kris** [comment]
Hi @stefanct - I finally found some time to take a look at this. It appears it is not trivial to support dual architectures, so instead I added checking of architecture. If there is a mismatch stackusage will output something like this:

    warning: libstackusage.so architecture (ELF 64-bit) does not appear
    to match <PROG> architecture (ELF 32-bit), analysis may fail.
    see https://github.com/d99kris/stackusage#technical-details

And the corresponding README section has been updated accordingly, with an example for `-m32`.
