### ISSUE TITLE
hang in armv7 platform 

### ISSUE THREAD

**Issue by tomasxu** [d99kris/stackusage#9]
I run this in my armv7 platform with musl-libc as libc, but resulting hang when I run this tool for my program

**Comment by d99kris** [comment]
Hi @tomasxu - could you help share what the console/terminal output is? 
What OS is the system running? Also, does it have `bash` installed?

If you have access to `strace` on that system, could you try to run the following and share the output:
```
strace stackusage yourprogram
```

If you have access to `lldb` on the system, could you try run this and share its output:
```
stackusage -d yourprogram
```

Thanks!

**Comment by d99kris** [comment]
Closing this issue due to insufficient information to further troubleshoot. Feel free to re-open the issue and add the information requested above. Thanks!
